apiVersion: v1
kind: Service
metadata:
  name: recommend-external
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: recommend
  sessionAffinity: None
  type: LoadBalancer
