apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysub
  namespace: dg0408-lifesub-ns
  labels:
    app: mysub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysub
  template:
    metadata:
      labels:
        app: mysub
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: mysub
        image: acrdigitalgarage02.azurecr.io/dg0408/mysub:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SERVER_PORT
          value: "8082"
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: mysub-config
        - secretRef:
            name: common-secret
        - secretRef:
            name: database-secret
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30
